name: "pastcollection"

services:
  pastcollection-postgres:
    container_name: pastcollection-postgres
    image: postgres:17.5-alpine
    restart: always
    environment:
      PGDATA: /pgdata
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - postgres_data:/pgdata
    ports:
      - "5432:5432"

volumes:
  postgres_data:
    driver: local
