name: "pastcollection"

services:
  pastcollection-postgres:
    container_name: pastcollection-postgres
    image: postgres:17.5-alpine
    restart: always
    environment:
      PGDATA: /pgdata
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - postgres_data:/pgdata
    ports:
      - "5432:5432"
  pastcollection-backend:
    container_name: pastcollection-backend
    build:
      dockerfile: ./backend/Dockerfile
      args:
        - APP_ENV=$APP_ENV
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app

  pastcollection-bot:
    container_name: pastcollection-bot
    network_mode: host
    env_file:
      - .env
    build:
      dockerfile: ./client/Dockerfile
      args:
        - APP_ENV=$APP_ENV
    volumes:
      - ./client:/app


volumes:
  postgres_data:
    driver: local
