// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/pastes": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Возвращает пасту по указанному фильтру",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pastes"
                ],
                "summary": "Найти одну пасту по фильтру",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Поиск по названию",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Айди автора",
                        "name": "userId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Айди в соц. сети",
                        "name": "socialId",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Айди пасты",
                        "name": "pasteId",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "Строгое или нестрогое совпадение в названии",
                        "name": "strict",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Найденная паста",
                        "schema": {
                            "$ref": "#/definitions/models.PasteModel"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/responses.UnauthorizedError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/responses.NotFoundError"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/responses.ValidationError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.InternalError"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Обновляет содержимое пасты",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pastes"
                ],
                "summary": "Обновить пасту",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Поиск по названию",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Айди автора",
                        "name": "userId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Айди в соц. сети",
                        "name": "socialId",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Айди пасты",
                        "name": "pasteId",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "Строгое или нестрогое совпадение в названии",
                        "name": "strict",
                        "in": "query"
                    },
                    {
                        "description": "Данные для обновления",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.UpdatePasteDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Обновленная паста",
                        "schema": {
                            "$ref": "#/definitions/models.PasteModel"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/responses.UnauthorizedError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/responses.NotFoundError"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/responses.ValidationError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.InternalError"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Создает новую пасту с указанным содержимым",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pastes"
                ],
                "summary": "Создать новую пасту",
                "parameters": [
                    {
                        "description": "Данные пасты",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.CreatePasteDto"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Созданная паста",
                        "schema": {
                            "$ref": "#/definitions/models.PasteModel"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/responses.UnauthorizedError"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/responses.ValidationError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.InternalError"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Удаляет пасту по указанному фильтру",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pastes"
                ],
                "summary": "Удалить пасту",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Поиск по названию",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Айди автора",
                        "name": "userId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Айди в соц. сети",
                        "name": "socialId",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Айди пасты",
                        "name": "pasteId",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "Строгое или нестрогое совпадение в названии",
                        "name": "strict",
                        "in": "query"
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/responses.UnauthorizedError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/responses.NotFoundError"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/responses.ValidationError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.InternalError"
                        }
                    }
                }
            }
        },
        "/api/pastes/count": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Возвращает общее количество паст в системе",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pastes"
                ],
                "summary": "Получить количество паст",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Поиск по названию",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Айди автора",
                        "name": "userId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Айди в соц. сети",
                        "name": "socialId",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Айди пасты",
                        "name": "pasteId",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "Строгое или нестрогое совпадение в названии",
                        "name": "strict",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Количество паст",
                        "schema": {
                            "$ref": "#/definitions/responses.CountResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/responses.UnauthorizedError"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/responses.ValidationError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.InternalError"
                        }
                    }
                }
            }
        },
        "/api/pastes/search": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Поиск паст по различным критериям",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pastes"
                ],
                "summary": "Поиск паст",
                "parameters": [
                    {
                        "type": "string",
                        "default": "DESC",
                        "description": "Сортировка результатов",
                        "name": "pagination[sort]",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "С какого айди начинать",
                        "name": "pagination[startFrom]",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Лимит результатов",
                        "name": "pagination[limit]",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "next",
                        "description": "Сторона",
                        "name": "pagination[order]",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Поиск по названию",
                        "name": "filter[search]",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Айди автора",
                        "name": "filter[userId]",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Айди в соц. сети",
                        "name": "filter[socialId]",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Айди пасты",
                        "name": "filter[pasteId]",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "Строгое или нестрогое совпадение в названии",
                        "name": "filter[strict]",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Список найденных паст",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.PasteModel"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/responses.UnauthorizedError"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/responses.ValidationError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.InternalError"
                        }
                    }
                }
            }
        },
        "/api/pastes/{id}/increment": {
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Увеличивает счетчик просмотров для конкретной пасты",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pastes"
                ],
                "summary": "Увеличить счетчик просмотров",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID пасты",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Обновленная паста",
                        "schema": {
                            "$ref": "#/definitions/models.PasteModel"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/responses.UnauthorizedError"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/responses.ValidationError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.InternalError"
                        }
                    }
                }
            }
        },
        "/api/users": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Найдёт пользователя по фильтру или вернёт 404",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Найти пользователя по фильтру",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID пользователя",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Уникальное имя",
                        "name": "username",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Отображаемое имя",
                        "name": "displayName",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Айди в соц. сети",
                        "name": "socialId",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "Если в true, тогда будет условие AND",
                        "name": "matchAll",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "Если в true, тогда строгое сравнение",
                        "name": "strict",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.UserModel"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/responses.UnauthorizedError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/responses.NotFoundError"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/responses.ValidationError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.InternalError"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Обновит пользователя или вернёт 404, 422",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Обновит пользователя",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID пользователя",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Уникальное имя",
                        "name": "username",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Отображаемое имя",
                        "name": "displayName",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Айди в соц. сети",
                        "name": "socialId",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "Если в true, тогда будет условие AND",
                        "name": "matchAll",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "Если в true, тогда строгое сравнение",
                        "name": "strict",
                        "in": "query"
                    },
                    {
                        "description": "Данные юзера",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.UpdateUserDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.UserModel"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/responses.UnauthorizedError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/responses.NotFoundError"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/responses.ValidationError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.InternalError"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Создаст пользователя или вернёт 422",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Создать пользователя",
                "parameters": [
                    {
                        "description": "Данные юзера",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.CreateUserDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.UserModel"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/responses.UnauthorizedError"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/responses.ValidationError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.InternalError"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Удалит пользователя или вернёт 404",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Удалить пользователя",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID пользователя",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Уникальное имя",
                        "name": "username",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Отображаемое имя",
                        "name": "displayName",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Айди в соц. сети",
                        "name": "socialId",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "Если в true, тогда будет условие AND",
                        "name": "matchAll",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "Если в true, тогда строгое сравнение",
                        "name": "strict",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.UserModel"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/responses.UnauthorizedError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/responses.NotFoundError"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/responses.ValidationError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.InternalError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dtos.CreatePasteDto": {
            "type": "object",
            "required": [
                "paste",
                "title",
                "userId"
            ],
            "properties": {
                "paste": {
                    "type": "string",
                    "maxLength": 2096,
                    "minLength": 1
                },
                "title": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 1
                },
                "userId": {
                    "type": "integer",
                    "minimum": 1
                }
            }
        },
        "dtos.CreateUserDto": {
            "type": "object",
            "required": [
                "displayName",
                "socialId",
                "username"
            ],
            "properties": {
                "displayName": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 1
                },
                "socialId": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                },
                "username": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 1
                }
            }
        },
        "dtos.UpdatePasteDto": {
            "type": "object",
            "required": [
                "paste",
                "title"
            ],
            "properties": {
                "paste": {
                    "type": "string",
                    "maxLength": 2096,
                    "minLength": 1
                },
                "title": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 1
                }
            }
        },
        "dtos.UpdateUserDto": {
            "type": "object",
            "required": [
                "displayName",
                "username"
            ],
            "properties": {
                "displayName": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 1
                },
                "username": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 1
                }
            }
        },
        "models.PasteModel": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "paste": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "userId": {
                    "type": "integer"
                },
                "views": {
                    "type": "integer"
                }
            }
        },
        "models.UserModel": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "displayName": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "socialId": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "responses.CountResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                }
            }
        },
        "responses.InternalError": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "responses.NotFoundError": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "responses.UnauthorizedError": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "responses.ValidationError": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "violations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/responses.Violation"
                    }
                }
            }
        },
        "responses.Violation": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "propertyPath": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "API Key authentication without Bearer prefix",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Pastes API",
	Description:      "Апишка для моего личного бота для коллекционирования паст",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
